### ISSUE TITLE
Boundary Conditions

### ISSUE THREAD

**Issue by ygtsdk** [jamiebull1/geomeppy#179] opened 2020-01-20 03:13 UTC
Hello,
I am new at this site and using EnergyPlus.
First of all I would like to thank you developing this useful tool.
My question is about the boundary conditions of ceilings.
While creating buildings with multiple stories I realized that the ceiling (between stories) boundary conditions are set as outdoor and they are wind exposed.

Do we need to fix those ourselves or is there a solution for this problem in Geomeppy.

Thank you in advance.

**Comment by jamiebull1** [comment] 2022-11-11 12:18
Duplicate of #205

**Closed by jamiebull1** 2022-11-11 12:18 UTC
Labels: duplicate
